#Load the custom files
just_the_docs:
  custom_css:
    - custom

# Markdown & Formatting 
markdown: kramdown 
kramdown: 
  input: GFM

# GitHub Pages Settings
plugins: 
  - jekyll-include-cache

# GitHub Pages Jekyll Theme
remote_theme: just-the-docs/just-the-docs 

# Dark mode 
color_scheme: dark
 
 # Site Identity
title: "Cyberfolio"
description: "Hands-on labs, investigations, and security analysis."

# Google Analytics Tracking
ga_tracking: "G-GK403M7RGP"
ga_tracking_anonymize_ip: true # Optional: Enables GDPR compliant tracking

# Collections 
collections: 
  labs: 
    output: true 
    permalink: /labs/:name/
  writeups: 
    output: true 
    permalink: /writeups/:name/
  projects: 
    output: true 
    permalink: /projects/:name/
